### ISSUE TITLE
Keeps on crashing in BoofCV's CI

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/ddogleg#21]
```TestWrapFeatureToSceneRecognition > Binary > learn_then_select() FAILED
    java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at org.ddogleg.clustering.kmeans.StandardKMeans.matchPointsToClusters(StandardKMeans.java:245)
        at org.ddogleg.clustering.kmeans.StandardKMeans.process(StandardKMeans.java:151)
        at boofcv.alg.scene.vocabtree.LearnHierarchicalTree.processLevel(LearnHierarchicalTree.java:142)
        at boofcv.alg.scene.vocabtree.LearnHierarchicalTree.process(LearnHierarchicalTree.java:120)
        at boofcv.abst.scene.nister2006.FeatureSceneRecognitionNister2006.learnModel(FeatureSceneRecognitionNister2006.java:144)
        at boofcv.abst.scene.WrapFeatureToSceneRecognition.learnModel(WrapFeatureToSceneRecognition.java:72)
        at boofcv.abst.scene.GenericSceneRecognitionChecks.learn_then_select(GenericSceneRecognitionChecks.java:103)```

**Comment by lessthanoptimal** [comment]
```TestWrapFeatureToSceneRecognition > Binary > learn_then_select() FAILED
    java.lang.NullPointerException: Cannot read field "data" because "a" is null
        at boofcv.alg.descriptor.DescriptorDistance.hamming(DescriptorDistance.java:234)
        at boofcv.struct.kmeans.TuplePointDistanceHamming.distance(TuplePointDistanceHamming.java:34)
        at boofcv.struct.kmeans.TuplePointDistanceHamming.distance(TuplePointDistanceHamming.java:30)
        at org.ddogleg.clustering.kmeans.StandardKMeans.findBestMatch(StandardKMeans.java:262)
        at org.ddogleg.clustering.kmeans.StandardKMeans.matchPointsToClusters(StandardKMeans.java:247)
        at org.ddogleg.clustering.kmeans.StandardKMeans.process(StandardKMeans.java:156)
        at boofcv.alg.scene.vocabtree.LearnHierarchicalTree.processLevel(LearnHierarchicalTree.java:142)
        at boofcv.alg.scene.vocabtree.LearnHierarchicalTree.process(LearnHierarchicalTree.java:120)
        at boofcv.abst.scene.nister2006.FeatureSceneRecognitionNister2006.learnModel(FeatureSceneRecognitionNister2006.java:144)```

**Comment by lessthanoptimal** [comment]
```TestWrapFeatureToSceneRecognition > Binary > learn_then_select() FAILED
    java.lang.ArrayIndexOutOfBoundsException: Index 134278 out of bounds for length 2428
        at org.ddogleg.struct.DogArray_I32.set(DogArray_I32.java:298)
        at org.ddogleg.clustering.kmeans.StandardKMeans.matchPointsToClusters(StandardKMeans.java:248)
        at org.ddogleg.clustering.kmeans.StandardKMeans.process(StandardKMeans.java:156)
        at boofcv.alg.scene.vocabtree.LearnHierarchicalTree.processLevel(LearnHierarchicalTree.java:142)
        at boofcv.alg.scene.vocabtree.LearnHierarchicalTree.process(LearnHierarchicalTree.java:120)
        at boofcv.abst.scene.nister2006.FeatureSceneRecognitionNister2006.learnModel(FeatureSceneRecognitionNister2006.java:144)
        at boofcv.abst.scene.WrapFeatureToSceneRecognition.learnModel(WrapFeatureToSceneRecognition.java:72)
        at boofcv.abst.scene.GenericSceneRecognitionChecks.learn_then_select(GenericSceneRecognitionChecks.java:103)```

**Comment by lessthanoptimal** [comment]
```# J 9551 c2 org.ddogleg.clustering.kmeans.StandardKMeans.findBestMatch(Ljava/lang/Object;Lorg/ddogleg/struct/DogArray;)I (71 bytes) @ 0x00007f7ac0ad4c60 [0x00007f7ac0ad4ba0+0x00000000000000c0]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/runner/work/BoofCV/BoofCV/main/boofcv-recognition/core.2955)
#
# An error report file with more information is saved as:
# /home/runner/work/BoofCV/BoofCV/main/boofcv-recognition/hs_err_pid2955.log
Compiled method (c1)  176944 9240       3       org.ddogleg.struct.DogArray_I32::resize (11 bytes)
 total in heap  [0x00007f7ab9895790,0x00007f7ab9895b60] = 976
 relocation     [0x00007f7ab98958e8,0x00007f7ab9895920] = 56
 main code      [0x00007f7ab9895920,0x00007f7ab9895aa0] = 384
 stub code      [0x00007f7ab9895aa0,0x00007f7ab9895ae0] = 64
 oops           [0x00007f7ab9895ae0,0x00007f7ab9895ae8] = 8
 metadata       [0x00007f7ab9895ae8,0x00007f7ab9895af8] = 16
 scopes data    [0x00007f7ab9895af8,0x00007f7ab9895b18] = 32
 scopes pcs     [0x00007f7ab9895b18,0x00007f7ab9895b58] = 64
 dependencies   [0x00007f7ab9895b58,0x00007f7ab9895b60] = 8
Compiled method (c1)  176944 9536       3       boofcv.struct.feature.PackedTupleBigArray_B::getTemp (6 bytes)
 total in heap  [0x00007f7ab9b73290,0x00007f7ab9b735b8] = 808
 relocation     [0x00007f7ab9b733e8,0x00007f7ab9b73420] = 56
 main code      [0x00007f7ab9b73420,0x00007f7ab9b73500] = 224
 stub code      [0x00007f7ab9b73500,0x00007f7ab9b73540] = 64
 oops           [0x00007f7ab9b73540,0x00007f7ab9b73548] = 8
 metadata       [0x00007f7ab9b73548,0x00007f7ab9b73558] = 16
 scopes data    [0x00007f7ab9b73558,0x00007f7ab9b73570] = 24
 scopes pcs     [0x00007f7ab9b73570,0x00007f7ab9b735b0] = 64
 dependencies   [0x00007f7ab9b735b0,0x00007f7ab9b735b8] = 8```

**Comment by lessthanoptimal** [comment]
Eh seems to have fixed itself. Maybe fewer solar storms these days.
